- docs/AboutUs.md
- docs/team/swaminathanviswa.md
> Update Viswa's section on AboutUs page

- docs/AboutUs.md
- docs/team/tohjh.md
> Update Jia Han's section on AboutUs page

- docs/AboutUs.md
- docs/team/dessnowy.md
> Update Xiang Yu's section on AboutUs page

- docs/_config.yml
- docs/_sass/minima/_base.scss
This changes the heading of the github pages and the link to our team project's repo as well.
Closes #27
> Update title and repository name in yml file

- docs/index.md
> Add Acknowledgement of original source code

- docs/index.md
> Update readme (A4)

- docs/UserGuide.md
> Update placeholder text of AB3

- docs/AboutUs.md
> Delete placeholder text in AboutUs.md

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Github.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
This PR adds GitHub into the add command feature, allowing GitHub account username to be specified in Addressbook
Updates #56
> Branch add GitHub account feature

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Telegram.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/person/TelegramTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
This PR does the addition of the telegram field into the input and be able to parse it. However, it does not show in the UI yet since that part has not been edited yet.
> Add Telegram as input and parse it

- src/main/java/seedu/address/logic/commands/AddGradeCommand.java
- src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/assignment/Assignment.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/assignment/AssignmentTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
This commit handles input and parsing of adding grades. Error handling and display are not implemented yet.
> Add input and parsing of adding grades

- src/main/java/seedu/address/model/person/Github.java
- src/test/java/seedu/address/model/person/GithubTest.java
Comprehensive of GitHub class to ensure that the methods perform as expected, correct errors are thrown.
In particular, the username regex needs to be changed to adhere to strict naming conventions of username by GitHub.
Closes #70
> Add tests for GitHub class

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
> Update usage text for DeleteCommand

- docs/UserGuide.md
User guide lacked proper documentation of the new add and command feature that takes in GitHub field. It now shows the new updated commands along with examples.
Closes #77
> Update user guide for add and edit command

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/model/person/Telegram.java
> Edit regex to include new character as input

- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/FilterCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
- src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Adds a new feature where users can filter the contacts by tag.
closes #79.
> New feature: filter contacts by tags

- src/main/java/seedu/address/MainApp.java
Fixes crash on start when the assignment.json data is missing from the folder.
> Fix crash when assignment.json is missing

- docs/UserGuide.md
> Update user guide for delete and filter command

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
Open URL button provides users who prefer typing to easily launch the user guide on their browser from AddressBook.
Closes #84
> Add open URL button to help page

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/commands/AddGradeCommand.java
- src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/assignment/Assignment.java
- src/main/java/seedu/address/model/assignment/PredefinedAssignment.java
- src/main/java/seedu/address/model/assignment/PredefinedAssignmentsData.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/storage/assignment/JsonSerializablePredefinedAssignmentData.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
> Handle errors and sanitize inputs while adding grades

- build.gradle
- src/main/java/seedu/address/commons/core/Browser.java
- src/main/java/seedu/address/commons/core/FunctionalBrowser.java
- src/main/java/seedu/address/logic/commands/GitHubCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/GitHubCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/commons/core/FunctionalBrowserTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/GitHubCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/GitHubCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/testutil/NonFunctionalBrowser.java
Closes #97 
The GitHub command allows users to launch a contact's GitHub repo using `github n/NAME`.
**Valid names:** Names already in the Address Book (and has a GitHub account field)
**Invalid names:** Names not in the Address Book
> Branch add GitHub command

- docs/UserGuide.md
User guide better reflects the state of the github command.
Closes #104
> Update user guide for github command

- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/ViewWindow.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ViewWindow.fxml
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Closes #95 
Currently, a simple view at the side with the same details as the person card.
To add to dg: view n/name
> Implement view command to show details

- build.gradle
- src/main/java/seedu/address/logic/commands/ExportCommand.java
- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ExportCommandParser.java
- src/main/java/seedu/address/logic/parser/ImportCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/assignment/Assignment.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/data/invalidImport.csv
- src/test/data/testExport.csv
- src/test/data/testImport.csv
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/ExportCommandTest.java
- src/test/java/seedu/address/logic/commands/GitHubCommandTest.java
- src/test/java/seedu/address/logic/commands/ImportCommandTest.java
- src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
- src/test/resources/view/UiPartTest/testImport.csv
> Branch add import export

- docs/UserGuide.md
> Update user guide for sort command

- docs/DeveloperGuide.md
- docs/diagrams/ArchitectureSequenceDiagram.puml
> Update sequence diagram in architecture

- src/main/java/seedu/address/logic/commands/SortCommand.java
> Fix spacing in error messaage of sort command

- src/main/java/seedu/address/logic/commands/FilterCommand.java
> Fix spacing in FilterCommand usage message

- src/main/java/seedu/address/logic/commands/EditCommand.java
> Update edit command

- src/main/java/seedu/address/logic/Messages.java
> Improve error message for invalid person

- src/main/java/seedu/address/logic/commands/EditCommand.java
The error message for edit command missed out on telegram field as optional input.
Closes #188
> Edit UI for edit command

- src/main/java/seedu/address/logic/commands/AddGradeCommand.java
This allows the weeks attended data to be stored and preserved when addGrade command is used.
Closes #158
> Add weeks attended as a parameter to Person object

- src/main/java/seedu/address/commons/core/FunctionalBrowser.java
- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/CsvRowParser.java
- src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Abstract out constants in some methods to adhere to java coding standard.
Closes #205
> Abstract constants from certain methods

- src/main/java/seedu/address/model/tag/Tag.java
> Change Tag to be case insensitive

- src/main/java/seedu/address/logic/commands/AddGradeCommand.java
- src/main/java/seedu/address/logic/commands/RemoveGradeCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
> Change command word to be case insensitive

- docs/UserGuide.md
- src/main/java/seedu/address/model/UserPrefs.java
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
> Rename storgae file to konTActs.json

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddGradeCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExportCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/GitHubCommand.java
- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/logic/commands/MarkCommand.java
- src/main/java/seedu/address/logic/commands/RemoveGradeCommand.java
- src/main/java/seedu/address/logic/commands/UnmarkCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> Add short form for commands

- build.gradle
> Rename jar file

- docs/_markbind/layouts/default.md
> Remove tutorial section

- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
> Improve error message for sort

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AddGradeCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/GitHubCommand.java
- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/MarkCommand.java
- src/main/java/seedu/address/logic/commands/RemoveGradeCommand.java
- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/commands/UnmarkCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/ui/HelpWindow.java
Include the shortcut forms of message usage examples.
Closes #273
> Update command usage message

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_markbind/variables.md
- docs/stylesheets/main.css
> Add page breaks to user and developer guide

- docs/UserGuide.md
> Update known issues in user guide to reflect why certain fields are not on shown in person card

- docs/UserGuide.md
> Update input for unused parameters

- docs/UserGuide.md
> Update Sort user guide

- src/main/java/seedu/address/logic/parser/CsvAssignmentParser.java
> Fix csv import

- src/main/java/seedu/address/commons/core/FunctionalBrowser.java
- Added logging to FunctionalBrowser class.
> Improve code quality

- docs/DeveloperGuide.md
- docs/diagrams/addSequenceDiagram.puml
> Add AddCommand implementation
